task:
  use_compute_credits: true
  container:
    image: ghcr.io/canonical/snapcraft:8_core24
    cpu: 1
    memory: 2G
  timeout_in: 20m
  env:
    DOCKER_PACKAGES: "snapcraft"
  install_packages_script:
    - apt-get update 
  snapcraft_pull_script:
    - snapcraft pull
  ci_script:
    - snapcraft
