task:
  use_compute_credits: true
  container:
    image: ubuntu:20.04
    cpu: 1
    memory: 2G
  timeout_in: 20m
  install_packages_script:
    - apt update
    - apt install snapd
    - snap install snapcraft 
  snapcraft_pull_script:
    - snapcraft pull
  ci_script:
    - snapcraft
